/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { TxHashStore, TxHashStoreInterface } from "../TxHashStore";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "HashRecorded",
    type: "event",
  },
  {
    inputs: [],
    name: "getCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
    ],
    name: "record",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102d7806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80636b2fafa914610046578063a87d942c14610076578063b5c645bd14610094575b600080fd5b610060600480360381019061005b919061018e565b6100b0565b60405161006d91906101d4565b60405180910390f35b61007e6100d7565b60405161008b91906101fe565b60405180910390f35b6100ae60048036038101906100a99190610245565b6100e3565b005b60008082815481106100c5576100c4610272565b5b90600052602060002001549050919050565b60008080549050905090565b60008190806001815401808255809150506001900390600052602060002001600090919091909150553373ffffffffffffffffffffffffffffffffffffffff16817fdf45777f4cfff4c462017cdbd5672e1db1c66d3ada611bdb36ecdbaca7714dfa60405160405180910390a350565b600080fd5b6000819050919050565b61016b81610158565b811461017657600080fd5b50565b60008135905061018881610162565b92915050565b6000602082840312156101a4576101a3610153565b5b60006101b284828501610179565b91505092915050565b6000819050919050565b6101ce816101bb565b82525050565b60006020820190506101e960008301846101c5565b92915050565b6101f881610158565b82525050565b600060208201905061021360008301846101ef565b92915050565b610222816101bb565b811461022d57600080fd5b50565b60008135905061023f81610219565b92915050565b60006020828403121561025b5761025a610153565b5b600061026984828501610230565b91505092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fdfea264697066735822122061b20ed7dc4b320aec8d2b19aa2b08aab3c28a20bbf273ecf37ac7f937a1343d64736f6c63430008140033";

type TxHashStoreConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TxHashStoreConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TxHashStore__factory extends ContractFactory {
  constructor(...args: TxHashStoreConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TxHashStore & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TxHashStore__factory {
    return super.connect(runner) as TxHashStore__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TxHashStoreInterface {
    return new Interface(_abi) as TxHashStoreInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): TxHashStore {
    return new Contract(address, _abi, runner) as unknown as TxHashStore;
  }
}
