/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TxHashStoreInterface extends Interface {
  getFunction(
    nameOrSignature: "getCount" | "getHash" | "record"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "HashRecorded"): EventFragment;

  encodeFunctionData(functionFragment: "getCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "record", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "getCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "record", data: BytesLike): Result;
}

export namespace HashRecordedEvent {
  export type InputTuple = [hash: BytesLike, sender: AddressLike];
  export type OutputTuple = [hash: string, sender: string];
  export interface OutputObject {
    hash: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TxHashStore extends BaseContract {
  connect(runner?: ContractRunner | null): TxHashStore;
  waitForDeployment(): Promise<this>;

  interface: TxHashStoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCount: TypedContractMethod<[], [bigint], "view">;

  getHash: TypedContractMethod<[index: BigNumberish], [string], "view">;

  record: TypedContractMethod<[hash: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHash"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "record"
  ): TypedContractMethod<[hash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "HashRecorded"
  ): TypedContractEvent<
    HashRecordedEvent.InputTuple,
    HashRecordedEvent.OutputTuple,
    HashRecordedEvent.OutputObject
  >;

  filters: {
    "HashRecorded(bytes32,address)": TypedContractEvent<
      HashRecordedEvent.InputTuple,
      HashRecordedEvent.OutputTuple,
      HashRecordedEvent.OutputObject
    >;
    HashRecorded: TypedContractEvent<
      HashRecordedEvent.InputTuple,
      HashRecordedEvent.OutputTuple,
      HashRecordedEvent.OutputObject
    >;
  };
}
